### ISSUE TITLE
Improve the third Pricing Table Item block positioning

### ISSUE THREAD

**Issue by richtabor** [coblocks/coblocks#279]
Currently, the third pricing table is placed below the first and second tables. This works, but when a user sets the alignment of the parent Pricing Table block to either wide or full, the third table should then sit beside the other two. 

[Related support ticket on WordPress.org](https://wordpress.org/support/topic/pricing-table-wrong-filling-up-the-row/#post-11198925)

Currently, on wide and full alignments - this happens:
<img width="1199" alt="screenshot 2019-02-12 16 28 12" src="https://user-images.githubusercontent.com/1813435/52669069-38fbf100-2ee3-11e9-81bc-8bf6a5f4cc5e.png">

**Comment by richtabor** [comment]
Was also reached out to about this issue [on Twitter](https://twitter.com/RobsWebDev/status/1095737529637261317).

**Comment by Florynx** [comment]
Solution (stands well for 4 columns also): 
modify in dist/blocks.style.build.css line 15 the below percentages from 40% to 20%:
@media (min-width:600px) { 
.wp-block-coblocks-pricing-table-item {
		-ms-flex-preferred-size:40%;
		flex-basis: 40%; ....
Also, is resonable to change block menu options icons for columns nbr "1-2-3" to "3-4-5" because "1 price item" is not a table :-) and "2 price items" is rarely used/useful. The column nbr slider (now max.4) could be extended to max. 6 (for example).
In this case could be removed the above lines at all, and add:
.wp-block-coblocks-pricing-table__inner { align-items: stretch;}
